### ISSUE TITLE
Excel complains about exported files

### ISSUE THREAD

**Issue by AlexGustafsson** [AlexGustafsson/timekeep#1]
The exported files can be opened in Excel, but it complains, saying that it was corrupt. If one bypasses the prompt, however, one can view the sheet as intended.

Also see upstream: https://github.com/exceljs/exceljs/issues/739.

**Comment by AlexGustafsson** [comment]
The file will be corrupt and unrepairable if no timekeep is kept.

**Comment by AlexGustafsson** [comment]
Solved the above comment by disabling exportation if no timekeep is kept.

**Comment by AlexGustafsson** [comment]
Also, see upstream https://github.com/exceljs/exceljs/issues/1068.

**Comment by Siemienik** [comment]
this pieces of information could be helpful:


https://github.com/exceljs/exceljs/issues/732
https://github.com/exceljs/exceljs/issues/745
https://github.com/exceljs/exceljs/issues/35 
https://github.com/exceljs/exceljs/issues/106
https://github.com/exceljs/exceljs/issues/739

**Comment by AlexGustafsson** [comment]
"Solved" by moving to https://www.npmjs.com/package/xlsx-populate#Workbook.
